services:
  - type: web
    name: Entrenaconia
    env: node
    region: frankfurt
    plan: free
    branch: main
    buildCommand: ./render-build.sh
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        sync: false
      - key: VITE_API_PORT
        value: "10000"
      - key: DATABASE_URL
        sync: false
      - key: DB_SEARCH_PATH
        value: app,public
      - key: DB_NAME
        value: postgres
      - key: JWT_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
